PantherHacks/pantherhacks.dev

- components/footer.tsx
Checklist:
This pull request includes accessibility improvements to the `Footer` component in the `components/footer.tsx` file by adding `aria-label` attributes and improving the email input field.
Accessibility improvements:
* Added `aria-label` to the email input field to enhance screen reader support and specified the input type as `email`. (`components/footer.tsx`, [components/footer.tsxL14-R37](diffhunk://#diff-bd3f659ee78d8c923c9975bdb8842b2a346ff04023e42fe215c0d080ef5cf115L14-R37))
* Added `aria-label` attributes to social media links for better accessibility. (`components/footer.tsx`, [components/footer.tsxL14-R37](diffhunk://#diff-bd3f659ee78d8c923c9975bdb8842b2a346ff04023e42fe215c0d080ef5cf115L14-R37))
> [accessibility] Footer input autofill compatibility and ARIA labelling

- components/navbar.tsx
- components/ui/NavLink.tsx
Checklist:
This is targeting a merge into the draft navbar branch titled "navbar-stuff".
In this pull request, I added:
1.  Navbar responsiveness. There are no animations for the mobile dropdown, which is something we may want to take a look at later once we are polishing up the website (if we decide it's important to us). 
2. Additionally, I made a component called "navlink" that is used to create links specifically for the navbar. 
3. Finally, I added ARIA labels for accessibility purposes on the icons.
> [additions] Navbar Mobile Responsiveness and Componentization

- components/navbar.tsx
- components/ui/NavLink.tsx
Checklist:
This pull request includes several changes to the `Navbar` component and the `NavLink` component in the `components` directory. The changes mainly focus on updating variants and improving the user interface.
* Updated the `NavLink` variant from `"icon"` to `"logo"` for the home link. This change was made in two places within the `Navbar` component. [[1]](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L42-R42) [[2]](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L120-R120)
* Changed the text from "APPLICATION OPEN SOON" to "APPLY" for the application link.
* Corrected the `alt` text for the Instagram icon from "Discord Icon" to "Instagram Icon".
* Added a new `logo` variant and updated the `icon` variant to …
> [fix] Improved margin for social navbar icons and other fixes

- components/footer/footer.tsx
- components/navbar.tsx
Checklist:
This pull request includes updates to the `Footer` and `Navbar` components to use consistent and centralized link variables for social media links. 
Improvements to link management:
* [`components/footer/footer.tsx`](diffhunk://#diff-cf39e7cefe742c218198800379017a0c028629f42fbe950f0fd03ef6218dfedbL12-R12): Updated the GitHub link in the `FooterSocialLink` component to point to the correct repository URL.
* [`components/navbar.tsx`](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626R15-R18): Introduced centralized variables (`gitHubLink`, `discordLink`, `instagramLink`) for social media links and replaced hardcoded URLs with these variables. [[1]](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626R15-R18) …
> [fix + refactor] Updated GitHub Link

- components/navbar.tsx
Checklist:
This pull request includes updates to the `Navbar` component in the `components/navbar.tsx` file to add a new application link and modify the "APPLY" button.
Changes to `Navbar` component:
* Added a new constant `applicationLink` with the URL to the application form.
* Updated the "APPLY" button to use the `applicationLink` and removed the `cursor-not-allowed` class to enable the button.
> [added] Application Link on "Apply" Navigation Button

- package-lock.json
- package.json
Fix to change release v0.3.0 to v0.0.3 to follow convention of previous releases.
> [release] v0.0.3

- components/navbar.tsx
Checklist:
This pull request includes a small change to the `components/navbar.tsx` file. The change adds a drop shadow to the navigation bar for improved visual styling.
* [`components/navbar.tsx`](diffhunk://#diff-697415f51799297bd64388e550f60789de985cb60aca6be2175bc512c9243626L42-R42): Added the `drop-shadow-lg` class to the `nav` element to enhance the visual appearance with a drop shadow.
> [added] Added Drop Shadow to the Navbar

- app/(main)/_components/heading.tsx
- app/(main)/_components/mobileheading.tsx
- components/footer/footer.tsx
- components/navbar.tsx
- lib/dates.ts
- lib/links.ts
Checklist:
Closes #16
This pull request includes updates to centralize and utilize hackathon date information and external links across multiple components. The most important changes include the addition of a new `hackathonDateInfo` object, the use of this object in various components, and the centralization of external links.
Centralizing hackathon date information:
* [`lib/dates.ts`](diffhunk://#diff-4e882006bef42d9d2d6a27e1b24e2b38d77cd27fefb94bd3d66cb12f354ff0a4R1-R11): Added a new `hackathonDateInfo` object to define date information for the hackathon.
* [`app/(main)/_components/heading.tsx`](diffhunk://#diff-38bcb41921a40de8ae1ed55132363f783274dc56e1bb2df9643e1a6d5c4128b4R11-R12): Updated the heading component to use `hackathonDateInfo` for the hackathon year and date string. …
> [addition][fix] Date and Link Constants, Fix Mobile Apply Button

- app/(main)/_components/faqs-section.tsx
Checklist:
Closes #29
This pull request includes significant updates to the `FaqsSection` component in the `app/(main)/_components/faqs-section.tsx` file. The changes involve importing additional modules and updating the FAQ content to reflect detailed information about the PantherHacks event.
Updates to FAQ content:
* Updated the questions and answers to provide detailed information about PantherHacks, including what it is, when and where it will be held, how to apply, cost, eligibility, and additional event details.
Imports added:
* Added imports for `Link` from `next/link`, `hackathonDateInfo` from `@/lib/dates`, and `applicationLink` from `@/lib/links`.
> [added] FAQ starter questions

- app/(main)/_components/about-section.tsx
- app/(main)/_components/faqs-section.tsx
- components/ui/accordion.tsx
Checklist:
This pull request includes changes to improve the responsiveness and accessibility of the `AboutSection` and `FaqsSection` components in the main application.
Improvements to responsiveness:
* [`app/(main)/_components/about-section.tsx`](diffhunk://#diff-db21f8aa87abe79e2eff49e1e588a583209f28d581b6030b9b0a47e95595abb7L7-R7): Adjusted the horizontal margin of the paragraph element to be more responsive across different screen sizes by using `mx-8 sm:mx-20 md:mx-24`.
Improvements to accessibility:
* [`app/(main)/_components/faqs-section.tsx`](diffhunk://#diff-da0ab51f7e03a171ce8c99ceaea66adccac0b1f0b91b460b7f3ab0cf75d37f54L63-R65): Added a `text-start` class to the `AccordionTrigger` to ensure the text is aligned to the start, improving readability.
> [fix] Mobile responsiveness for text

- .github/ISSUE_TEMPLATE/01--issue-with-website.yml
- .github/ISSUE_TEMPLATE/02--feature-request.yml
- .github/ISSUE_TEMPLATE/config.yml
Checklist:
This pull request introduces new issue templates for reporting website bugs and requesting new features, as well as enabling blank issues. The most important changes include the addition of detailed templates for both bug reports and feature requests, and a configuration change to allow blank issues.
New issue templates:
* [`.github/ISSUE_TEMPLATE/01--issue-with-website.yml`](diffhunk://#diff-ecf519bb079592393713ab513db580b92f231303229bd1ec8b3745ba84c76bedR1-R56): Added a template for reporting software bugs on the website, including fields for issue description, affected pages, steps to reproduce, expected behavior, screenshots, system information, and additional context.
* [`.github/ISSUE_TEMPLATE/02--feature-request.yml`](diffhunk://#diff-6d3f41f281d0ce14966567ff648d739c627b7 …
> [added] Issue templates

- app/(main)/_components/track.tsx
- app/(main)/_components/tracks-section.tsx
- components/navbar.tsx
- components/ui/dialog.tsx
- package-lock.json
- package.json
Checklist:
Closes #37
Closes #46
This pull request introduces a new dialog component and integrates it into the track display section, along with some minor UI adjustments and dependency updates. The most important changes include the addition of the dialog component, updates to the track section to include popups, and adjustments to the navbar z-index.
* [`components/ui/dialog.tsx`](diffhunk://#diff-ba221113eac7c71476db82fb5db4c480fd556a56ed1ddd8e77aa8b85f67628bfR1-R97): Added a new dialog component using `@radix-ui/react-dialog`, including various subcomponents like `DialogTrigger`, `DialogContent`, `DialogHeader`, and `DialogTitle`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18): Added `@radix-ui/react-dialog` to dependencies.
* …
> [added + fix] Track information modal + formatting fixes

- app/(main)/_components/track.tsx
- app/(main)/_components/tracks-section.tsx
Checklist:
Closes #36
Closes #49
This pull request includes enhancements to the `Track` component and layout adjustments in the `TracksSection` component to improve visual spacing and alignment. The most important changes include adding new props to the `Track` component and updating the `TracksSection` component to utilize these new props for better layout control.
Enhancements to `Track` component:
* [`app/(main)/_components/track.tsx`](diffhunk://#diff-0854ade927e647b49f2178f6a1a12e7a85feda6ebd6727e1764156206acec622R11-R21): Added `leftOffset` and `rightOffset` optional boolean props to `ITrackProps` interface. Updated the `Track` component to use these props for conditional CSS class application to adjust the horizontal position of the track name. …
> [fix] Track Visual Fixes

- app/(main)/_components/main-content.tsx
- app/layout.tsx
Checklist:
Closes #53
This pull request includes minor changes to improve the layout and scrolling behavior in the application. The most important changes include adding hidden overflow properties to prevent unwanted scrolling.
Layout improvements:
* [`app/(main)/_components/main-content.tsx`](diffhunk://#diff-bca88fd766f976eac9a0531fdae69d12d05f26bb6ba8f820aaa45b94d2037427L21-R21): Added `overflow-y-hidden` to the main content container to prevent vertical overflow.
* [`app/layout.tsx`](diffhunk://#diff-eca96d2c09f31517696a26e1d0be4070e1fbab02831481bed006e275741d030bL50-R50): Added `overflow-x-hidden` to the HTML element to prevent horizontal overflow.
> [fix] Horizontal scroll on transition svg and main page

- app/(main)/_components/main-content.tsx
- package-lock.json
Checklist:
Closes #35
This pull request includes a change to the `app/(main)/_components/main-content.tsx` file, specifically modifying the `className` property of the header transition element to adjust its scaling and translation.
Styling adjustment:
* [`app/(main)/_components/main-content.tsx`](diffhunk://#diff-bca88fd766f976eac9a0531fdae69d12d05f26bb6ba8f820aaa45b94d2037427L28-R28): Changed the `className` property of the header transition element to use `scale-x-[125%]` and `-translate-x-14` for improved layout and appearance.
> [fix] WebKit svg gap for heading transition

- CODE_OF_CONDUCT.md
- README.md
Checklist:
Closes #63
This pull request includes significant updates to the documentation for the PantherHacks project. The most important changes involve the addition of a comprehensive Code of Conduct and enhancements to the README file to provide better guidance on installation and contribution.
* [`CODE_OF_CONDUCT.md`](diffhunk://#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2R1-R131): Added a detailed Contributor Covenant Code of Conduct to ensure a harassment-free and inclusive community. This includes sections on our pledge, standards, enforcement responsibilities, scope, enforcement guidelines, and attribution.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L5-R55): Enhanced the README file to include a new …
> [added] Improved readme + contributing code of conduct

- app/(main)/_components/_prizes/prizes-section.tsx
- app/(main)/_components/_team/team-section.tsx
- app/(main)/_components/about-section.tsx
- app/(main)/_components/faqs-section.tsx
- app/(main)/_components/tracks-section.tsx
- components/navbar.tsx
Checklist:
This pull request includes several updates to various sections of the main application to improve the visual layout and consistency. The most important changes include updates to image sources and styles, text formatting enhancements, and the addition of new images to the FAQs section.
* [`app/(main)/_components/_team/team-section.tsx`](diffhunk://#diff-71462656c13150bc10dbd75471bb507a225e716c1a260ad9e6c9e5509e86f946L10-R22): Updated the image source for the orange branch and adjusted the positioning and size of images to improve the layout.
* [`app/(main)/_components/tracks-section.tsx`](diffhunk://#diff-7ed78e2061636bac27afdd60e336fffd4f689df1be220e64a8ccd10e016e5319L21-R21): Adjusted the size and positioning of images for better visual consistency across different screen …
> [fix] Improved orange spacing and margins

- app/(main)/_components/_prizes/prizes-section.tsx
Checklist:
This pull request includes a small change to the `prizes-section.tsx` file. The change updates the text in the `PrizesSection` component to provide more detailed information about the prizes offered. 
* [`app/(main)/_components/_prizes/prizes-section.tsx`](diffhunk://#diff-e1d03cd3e18c3fbf323db9b06c547cafb7b938a82e0d8d487cdab3a57a6dfd8eL15-R18): Modified the description to specify that each member of the winning teams (consisting of 1-4 people) will receive a prize.
> [fix] Changed the wording of the prize section

- app/(main)/_components/_team/team-member.tsx
- app/(main)/_components/_team/team-section.tsx
- package-lock.json
Checklist:
This pull request includes changes to the `team-member` and `team-section` components to improve their layout and responsiveness. The most important changes include adding width constraints to the `TeamMember` component and modifying the layout of the `TeamSection` component to use a flexible grid system.
Improvements to layout and responsiveness:
* [`app/(main)/_components/_team/team-member.tsx`](diffhunk://#diff-a5f82668380117c931d120b853e50e60712098c6f3718dc1c3ddc27603589248L14-R14): Added width constraints to the `TeamMember` component to ensure consistent sizing across different screen sizes.
* [`app/(main)/_components/_team/team-section.tsx`](diffhunk://#diff-71462656c13150bc10dbd75471bb507a225e716c1a260ad9e6c9e5509e86f946L29-R29): Changed the layout of the `TeamSection` …
> [added] Team Member Flexbox and Centering

- app/(main)/_components/_team/team-member.css
Checklist:
This pull request includes minor changes to the `team-member.css` file. The changes adjust the text shadow properties for better visual appearance.
* [`app/(main)/_components/_team/team-member.css`](diffhunk://#diff-27748bd3d4a900871a6b04246c64a438154115b5fedd37e939c419a186d5e2f1L6-R10): Modified the `text-shadow` property for `.team-member-name` and `.team-member-role` classes to improve the visual effect.
> [fix] slightly decreased drop shadow for team member names

- package-lock.json
- package.json
Checklist:
This pull request includes a version update for the `pantherhacks.dev` project in the `package.json` file.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `0.0.9` to `1.0.0`.
> [release] v1.0.0 Release Prep - package update

- components/navbar.tsx
Checklist:
This pull request includes changes to the `Navbar` component in `components/navbar.tsx` to adjust the responsive design breakpoints and add a new heading element. The most important changes include modifying the media query breakpoints and adding a new heading for branding.
Responsive design adjustments:
* Changed the media query breakpoint from `805px` to `850px` for the desktop view of the navbar.
* Changed the media query breakpoint from `805px` to `850px` for the mobile view of the navbar.
Branding enhancement:
* Added a new heading element with the text "PANTHERHACKS" that is visible on small screens and above.
> [addition] Navbar Title

- app/(main)/_components/about-section.tsx
Checklist:
Closes #84 
This pull request includes a small change to the `AboutSection` component in the `app/(main)/_components/about-section.tsx` file. The change modifies the paragraph styling and content to improve readability and clarity.
Styling and content updates:
* Added a `max-w-[50rem]` class to the paragraph for better text width control.
* Updated the paragraph content to provide more detailed information about the PantherHacks event.
* Commented out the "APPLY NOW" button link for potential future use.
> [fix] Max width sizing for about section text

- app/(main)/_components/about-section.tsx
- app/(main)/_components/countdown.tsx
- app/(main)/_components/main-content.tsx
- lib/countdown.ts
- lib/dates.ts
- package-lock.json
Checklist:
This pull request introduces a countdown timer component to the main content of the application, which displays the time remaining until key hackathon events. The most important changes include the addition of the `Countdown` component, updates to the main content structure, and the inclusion of countdown descriptions and hackathon date information.
* [`app/(main)/_components/countdown.tsx`](diffhunk://#diff-ea1f44d41914038168b252e1805c51f086fc71f8c556e3ebb2f964cbcdc28579R1-R87): Added a new `Countdown` component that calculates and displays the time remaining until the hackathon starts, ends, or the application submission deadline.
* [`app/(main)/_components/main-content.tsx`](diffhunk://#diff-bca88fd766f976eac9a0531fdae69d12d05f26bb6ba8f820aaa45b94d2037427R8): Imported and …
> [added] Countdown Feature

- app/(main)/_components/countdown.tsx
- package-lock.json
- package.json
v1.1.0 $\rightarrow$ v1.1.1
This pull request includes minor updates to the `countdown.tsx` component and a version bump in the `package.json` file.
Styling adjustment:
* [`app/(main)/_components/countdown.tsx`](diffhunk://#diff-ea1f44d41914038168b252e1805c51f086fc71f8c556e3ebb2f964cbcdc28579L76-R76): Removed extra padding at the bottom of the countdown component's container.
Version update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the project version from 1.1.0 to 1.1.1.
> [release] v1.1.1

- package-lock.json
- package.json
> [release] v1.1.3

- app/(main)/_components/countdown.tsx
- package-lock.json
- package.json
This pull request includes several changes to the `Countdown` component in `countdown.tsx` and a version update in `package.json`. The changes primarily focus on improving the date and time calculations and updating the project version.
Improvements to date and time calculations:
* [`app/(main)/_components/countdown.tsx`](diffhunk://#diff-ea1f44d41914038168b252e1805c51f086fc71f8c556e3ebb2f964cbcdc28579L11-R27): Modified the calculation of `hackathonStartDate`, `hackathonEndDate`, and `applicationSubmissionDate` to correctly handle AM/PM times and ensure accurate conversion.
Codebase maintenance:
* [`app/(main)/_components/countdown.tsx`](diffhunk://#diff-ea1f44d41914038168b252e1805c51f086fc71f8c556e3ebb2f964cbcdc28579L73-R83): Removed a comment regarding dependencies in the `useEffect` …
> [release] v1.1.4

- app/globals.css
- app/rules/page.tsx
- lib/dates.ts
- package-lock.json
Checklist:
This pull request includes changes to the `app/rules/page.tsx`, `app/globals.css`, and `lib/dates.ts` files to add a new Rules page, update the hackathon date information, and improve the CSS styling.
New Rules page:
* [`app/rules/page.tsx`](diffhunk://#diff-35b3b1cb9e9bc276a49e9b1dd31b84b0c13ff05f7413dfd92c8f5c9916141108R1-R115): Added a new Rules page component that includes the hackathon spirit, competition rules, and references to Major League Hacking rules.
CSS styling improvements:
* [`app/globals.css`](diffhunk://#diff-79e0914d9fee5ca4432bdb002a24d700d31b5577265f4de3f90d5c292b9f1392R69-R72): Added a new CSS rule to add spacing between list items that are not the last child.
Hackathon date updates:
* [`lib/dates.ts`](diffhunk://#diff-4e882006bef42d9d2d6a27e1b24e2b38d77cd27 …
> [addition] Hackathon Rules Page

- app/(event)/live/_components/event-card.tsx
- app/(event)/live/_components/schedule-helpers.ts
Checklist:
Closes #106
This pull request enhances the `EventCard` component by introducing an "Add to Calendar" feature. The changes include importing a new icon and utility function, updating the UI to include a button for adding events to a calendar, and implementing the `addToCalendar` function to generate downloadable `.ics` files.
* Added an "Add to Calendar" button to the `EventCard` component, styled for responsiveness and accessibility. The button uses the `CalendarPlus2` icon and triggers the `addToCalendar` function when clicked. (`app/(event)/live/_components/event-card.tsx`, [[1]](diffhunk://#diff-725cab3f770854b86e76d4a3902d993ff747d7ecdb1d317d74caef9f0916a5d3R50-R51) [[2]](diffhunk://#diff-725cab3f770854b86e76d4a3902d993ff747d7ecdb1d317d74caef9f0916a5d3R64-R72)
* Implemented …
> [added] Add to calendar button on events

- app/(event)/live/_components/schedule-filters.tsx
- app/(event)/live/_components/schedule.tsx
- package-lock.json
Checklist:
Closes #105
This pull request introduces a new feature to filter the schedule by activity type and includes several UI improvements in the `ScheduleSection` component. The most important changes involve adding a `ScheduleFilters` component, integrating it into the schedule, and enhancing the layout and interactivity of the schedule UI.
* Added a new `ScheduleFilters` component (`app/(event)/live/_components/schedule-filters.tsx`) that allows users to toggle filters for different activity types (e.g., "Check-in," "Main Event"). The component dynamically updates the active filters using state management.
* Integrated the `ScheduleFilters` component into the `ScheduleSection` by importing it and managing its state (`activeFilters` and `setActiveFilters`) in the parent component. …
> [added] Live Schedule filters by event type

- app/(event)/countdown/page.tsx
- app/(event)/live/_components/important-link.tsx
- app/(event)/live/_components/important-links.tsx
- app/(event)/live/_components/schedule.tsx
- app/(event)/live/page.tsx
- lib/links.ts
Checklist:
Closes #113
This pull request introduces new features and UI improvements for the live event pages, including the addition of an "Important Links" section, a new reusable `ImportantLink` component, and minor UI adjustments. Below are the most significant changes grouped by theme:
* Added a new `ImportantLinksSection` component to display key links (e.g., Devpost, Rules, FAQs, Discord) with icons and descriptions on the live event page (`app/(event)/live/_components/important-links.tsx`).
* Created a reusable `ImportantLink` component for rendering individual links with optional icons or images (`app/(event)/live/_components/important-link.tsx`).
* Integrated the `ImportantLinksSection` into the live event page layout, placing it above the schedule section …
> [added] Important Links section on `/live` page

- app/(application)/apply/page.tsx
- app/(event)/live/page.tsx
- app/(event)/rules/page.tsx
- app/(event)/schedule/page.tsx
- app/(main)/page.tsx
- app/not-found.tsx
- components/navbar/navbar.css
- components/navbar/navbar.tsx
- package-lock.json
Checklist:
Closes #115
This pull request focuses on refactoring the `Navbar` component, enhancing its styling, and updating its usage across multiple pages. The key changes include renaming and relocating the `Navbar` component, introducing a new "LIVE" button with animated styling, and updating all references to the `Navbar` component to reflect its new location. Additionally, a new CSS class for neon text styling was added.
* The `Navbar` component was renamed and moved from `components/navbar.tsx` to `components/navbar/navbar.tsx`. All imports across various pages were updated to reflect this change. [[1]](diffhunk://#diff-7dd8e905973a5902e9ebf1519bbb29807b5a5148b01aee4089bd59464eed0620L6-R6) [[2]](diffhunk://#diff-26fcd2a2fe7098ff503de3d84982b0dbfab3c620ea3262dd6e709c3bdeef8ef2L4-R4) …
> [added] Replaced `APPLY` nav button with `LIVE` nav button

- app/(event)/live/_components/important-link.tsx
- components/countdown.tsx
- components/navbar/navbar.tsx
- package-lock.json
Checklist:
This pull request introduces several UI adjustments to improve responsiveness and usability across components. Key changes include resizing elements for better adaptability on smaller screens, modifying text sizes for consistency, and removing unnecessary attributes in the `Navbar` component.
* [`app/(event)/live/_components/important-link.tsx`](diffhunk://#diff-c7f085e306c5fd924abf633028beee7dcb19cab83d1d7de3f5fbe1c93826af92L15-R24): Adjusted dimensions of the `ImportantLink` component for better responsiveness by introducing smaller sizes for non-`sm` screens and scaling icons accordingly.
* [`components/countdown.tsx`](diffhunk://#diff-7a5111ab4da9ae21cd9ac0cadb513390658eb20b118b626bfcb1f62e6410f537L95-R95): Increased the default text size for the countdown component from …
> [fix] Countdown, Navbar Link, and Important Link Fixes

- app/(event)/live/_components/event-card.tsx
- app/(event)/live/_components/live.css
- app/(event)/live/_components/schedule.tsx
- components/ui/switch.tsx
- package-lock.json
- package.json
Checklist:
Closes #112
This pull request introduces several updates to improve the event scheduling UI and enhance the user experience. Key changes include adding a "Show Previous Events" toggle, implementing a "LIVE" indicator for ongoing events, and introducing a reusable `Switch` component. Styling updates and dependency additions are also included.
* Added a "LIVE" indicator for ongoing events, including a pulsating animation and neon-style text, to highlight live events. (`app/(event)/live/_components/event-card.tsx`, `app/(event)/live/_components/live.css`) [[1]](diffhunk://#diff-725cab3f770854b86e76d4a3902d993ff747d7ecdb1d317d74caef9f0916a5d3R78-R96) [[2]](diffhunk://#diff-a8f6169bd601133c41da8b42c848e7c1f48f11571eda2dbab1f78fb81ade293aL4-R48)
* Updated the `EventCard` component to …
> [addition] Previous date filter

- app/(event)/countdown/page.tsx
Checklist:
This pull request makes improvements to the `CountdownPage` component in `app/(event)/countdown/page.tsx`, focusing on enhancing user interaction and fixing a typo in a variable name. The changes ensure better cursor visibility management and improve code readability.
* Updated the `handleMouseMove` function to set the cursor style to "default" when the mouse moves and "none" after inactivity, enhancing the user experience. Also ensured the cursor style is reset to "default" in the cleanup function.
* Fixed a typo in the variable name `timeAmountInMiliseconds`, correcting it to `timeAmountInMilliseconds` for consistency and clarity.
> [fix] Cursor will hide on countdown page automatically

- app/(event)/live/_components/important-link.tsx
- package-lock.json
- package.json
This pull request introduces a fullscreen toggle feature to the countdown page and updates the project version in `package.json`. The most important changes include adding state and event listeners for fullscreen functionality, implementing a button to toggle fullscreen mode, and updating the project version.
* [`app/(event)/countdown/page.tsx`](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3L6-R13): Added a new `isFullscreen` state to track fullscreen mode and a `toggleFullscreen` function to enter/exit fullscreen. Also added a `useEffect` hook to listen for fullscreen changes and update the state accordingly. [[1]](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3L6-R13) …
> [release] v1.3.1

- components/countdown.tsx
- components/ui/skeleton.tsx
- lib/countdown.ts
- package-lock.json
Checklist:
This pull request enhances the `Countdown` component by adding a loading skeleton for better user experience and updates the countdown descriptions for improved clarity. Additionally, a reusable `Skeleton` component is introduced for consistent styling across the application.
* Added a loading skeleton (`Skeleton` component) to display placeholders when `countdownString` or `descriptionString` is not available. The skeleton adapts its size based on the `size` prop (`large` or `default`). (`components/countdown.tsx`: [[1]](diffhunk://#diff-7a5111ab4da9ae21cd9ac0cadb513390658eb20b118b626bfcb1f62e6410f537R93-R95) [[2]](diffhunk://#diff-7a5111ab4da9ae21cd9ac0cadb513390658eb20b118b626bfcb1f62e6410f537R104-R107) [[3]](diffhunk://#diff-7a5111ab4da9ae21cd9ac0cadb513390658eb20b118b626bfc …
> [added + fixed] loading skeleton on countdown and wording change

- components/countdown.tsx
- components/ui/skeleton.tsx
- lib/countdown.ts
- package-lock.json
- package.json
Checklist:
This pull request is to release all changes since v1.3.1 to production deployment, establishing version v1.3.2. The changes are described below:
This pull request introduces a loading skeleton to the countdown component, updates countdown descriptions for clarity, and includes a minor version bump in `package.json`. Below are the most important changes grouped by theme:
* Added a `Skeleton` component in `components/ui/skeleton.tsx` to display a loading animation. This component uses a `div` with a pulse animation and accepts additional class names via props.
* Updated the `Countdown` component in `components/countdown.tsx` to show the `Skeleton` component when `countdownString` or `descriptionString` is not available. The skeleton adapts its size based on the `size` prop. …
> [release] v1.3.2

- app/(event)/live/_components/schedule.tsx
Checklist:
This pull request updates the error message displayed in the `ScheduleSection` component to improve its readability and provide clearer instructions to the user.
UI/UX improvements:
* [`app/(event)/live/_components/schedule.tsx`](diffhunk://#diff-f529b55f417aec5c23b8598505124966b3f8c147ed05697cb3edb263aa0e157fL136-R138): Enhanced the error message styling by adding `text-center` and `mx-10` classes for better alignment and spacing. Updated the message text to include a suggestion to check the user's connection before refreshing the page.
> [fix] Schedule error message formatting issue

- app/(event)/live/_components/schedule.tsx
- package-lock.json
- package.json
This pull request includes a minor update to improve the user experience in the `ScheduleSection` component and a version bump in the `package.json` file.
Improvements to user experience:
* [`app/(event)/live/_components/schedule.tsx`](diffhunk://#diff-f529b55f417aec5c23b8598505124966b3f8c147ed05697cb3edb263aa0e157fL136-R138): Updated the error message styling in the `ScheduleSection` component to include `text-center` and `mx-10` classes, ensuring better alignment and spacing for users when events fail to load. The error message text was also updated to suggest checking the connection before refreshing the page.
Version update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Incremented the application version from `1.3.2` to …
> [release] v1.3.3

- app/(event)/live/_components/schedule.tsx
Checklist:
This pull request updates the `ScheduleSection` component to improve the user experience by adding a message when there are no more upcoming events.
* [`app/(event)/live/_components/schedule.tsx`](diffhunk://#diff-f529b55f417aec5c23b8598505124966b3f8c147ed05697cb3edb263aa0e157fR241-R245): Added a conditional check to display a message, "There are no more upcoming events," when `showPrevEvents` is false and all events in `eventsByDay` have ended. This ensures users are informed when there are no future events.
> [added] Show a message when there are no upcoming events

- app/(event)/countdown/page.tsx
- components/countdown.tsx
- lib/countdown.ts
- package-lock.json
- package.json
Checklist:
This pull request introduces enhancements to the countdown page and countdown component, focusing on improving user experience during and after the hackathon. Key changes include adding confetti effects for hackathon completion, refining countdown descriptions, and dynamically handling screen resizing for visual elements.
* Added `react-confetti` to display confetti when the hackathon ends, using dynamic dimensions based on the container size. (`app/(event)/countdown/page.tsx`, `package.json`) [[1]](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3L3-R61) [[2]](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3R143-R174) [[3]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30)
* …
> [added] Confetti on hackathon completion

- app/(event)/countdown/page.tsx
- app/(event)/live/_components/schedule.tsx
- components/countdown.tsx
- lib/countdown.ts
- package-lock.json
- package.json
This pull request introduces several enhancements to the countdown and event-related pages, focusing on improving user experience, adding visual elements, and refining messaging. The key changes include adding confetti effects for the hackathon conclusion, improving responsiveness, and updating messaging for completed events.
* Added a confetti animation using the `react-confetti` library, triggered when the hackathon ends. This includes dynamically resizing the confetti canvas based on the container's dimensions. (`app/(event)/countdown/page.tsx`, [[1]](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3L3-R61) [[2]](diffhunk://#diff-de113fe06ab5716fb5c07a7196d924d08d6f8d792cd292339f98a052b8cddbb3R143-R174)
* Introduced logic to determine the hackathon's …
> [release] v1.3.4
